0PWAIIA: "Windows 0P Windows features like Recall" {
  style.fill: "#ffd580"
}

1PWAIIA: "Microsoft 1P Apps like Photos/Paint" {
  style.fill: "#ffd580"
}

AIF: "AI Fabric" {
  PSAPI: "PSAPI" {
    ONNX: "ONNX Runtime" {
      style.fill: "#b2f0e3"
      EP1: "IHV EP 1" {
        style.fill: "#ffc0cb"
      }
      EP2: "IHV EP 2" {
        style.fill: "#ffc0cb"
      }
    }
  }
  OCR: "OCR" {
    ONNX: "ONNX Runtime" {
      style.fill: "#b2f0e3"
      EP1: "IHV EP 1" {
        style.fill: "#ffc0cb"
      }
      EP2: "IHV EP 2" {
        style.fill: "#ffc0cb"
      }
    }
  }
}

AIF_REPLAT: "AI Fabric Replat" {
  PSAPI: "PSAPI"
  OCR: "OCR"
}

WinAIF: "Windows AI Foundry" {
  WinML: "Windows ML" {
    style.fill: "#d5b3ff"
    ONNX: "ONNX Runtime" {
      style.fill: "#b2f0e3"
      EP1: "IHV EP 1" {
        style.fill: "#ffc0cb"
      }
      EP2: "IHV EP 2" {
        style.fill: "#ffc0cb"
      }
    }
  }
}

IHV: "IHV" {
  EP1: "IHV EP 1" {
    style.fill: "#ffc0cb"
  }
  EP2: "IHV EP 2" {
    style.fill: "#ffc0cb"
  }
  style.fill: "#ffc0cb"
}

NPU: "NPU" {
  style.fill: "#87ceeb"
}

0PWAIIA -> AIF
1PWAIIA -> AIF

IHV.EP1 -> WinAIF.WinML.ONNX.EP1
IHV.EP2 -> WinAIF.WinML.ONNX.EP2

IHV.EP1 -> AIF.PSAPI.ONNX.EP1
IHV.EP2 -> AIF.PSAPI.ONNX.EP2

IHV.EP1 -> AIF.OCR.ONNX.EP1
IHV.EP2 -> AIF.OCR.ONNX.EP2

AIF_REPLAT.PSAPI -> WinAIF.WinML
AIF_REPLAT.OCR -> WinAIF.WinML

0PWAIIA -> AIF_REPLAT
1PWAIIA -> AIF_REPLAT

AIF.PSAPI.ONNX.EP1 -> NPU
AIF.PSAPI.ONNX.EP2 -> NPU
AIF.OCR.ONNX.EP1 -> NPU
AIF.OCR.ONNX.EP2 -> NPU
WinAIF.WinML.ONNX.EP1 -> NPU
WinAIF.WinML.ONNX.EP2 -> NPU
